config/routes.rb
BallInHand::Application.routes.draw do
  root :to => 'games#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :games
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/eight_ball.rb
class EightBall < Game
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :meta, :type
  has_many :result

  def self.record(type, winner, loser, meta = {})
    game = create_game(type, meta)
    create_results(winner, loser, game)
  end

  private

  def self.create_game(type, meta)
    Game.create type: type, meta: MultiJson.dump(meta)
  end

  def self.create_results(winner, loser, game)
    elo_winner = Elo::Player.new rating: winner.rating, games_played: winner.games_played
    elo_loser = Elo::Player.new rating: loser.rating, games_played: loser.games_played
    elo_winner.wins_from elo_loser

    Result.create player: winner, won: true, rating_after: elo_winner.rating, game: game
    Result.create player: loser, won: false, rating_after: elo_loser.rating, game: game
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :secret_key
  has_many :results

  validates_presence_of :name, :secret_key

  def rating
    last_result = results.last

    if last_result
      results.last.rating_after
    else
      1000 # Default rating (Magic number, I know :(
    end
  end

  def games_played
    results.count
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
  attr_accessible :rating_after, :won, :player, :game

  def opponent
    game.result.find { |r| r.player != player }.player
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @players = Player.all.sort_by { |player| - player.rating}
  end

  def new
    @players = Player.all
  end

  def create
    winner = params[:winner].to_i
    winner_secret_key = params[:winner_secret_key]
    loser  = params[:loser].to_i
    loser_secret_key = params[:loser_secret_key]
    game_type = params[:game_type].to_s

    winner = Player.find(winner)
    loser = Player.find(loser)

    authenticated = winner.secret_key == winner_secret_key && loser.secret_key == loser_secret_key

    if winner != loser && authenticated
      Game.record game_type, winner, loser
      redirect_to "/" # TODO: RETURN 200 AND SOME FANCY JSON FOR BACKBONE
    else
      # TODO: Error message
      @players = Player.all
      render :new
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])
    @results = @player.results.sort_by(&:created_at)
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])
    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/index.html.haml
.row
  .large-6.columns
    .new-game.center
      =link_to 'New Game', new_game_path, class: ['button', 'primary']
.row
  .small-2.large-12.columns
    .rating-table.center
      %h4 Ratings table
      %table.center
        %thead
          %tr
            %th{:width => "50"} Ranging
            %th{:width => "200"} Player
            %th{:width => "100"} Rating
            %th{:width => "150"} Games Played
        %tbody
          - @players.each_with_index do |player, index|
            %tr
              %td= index+1
              %td
                %a{href: "players/#{player.id}"}= player.name
              %td= player.rating
              %td= player.games_played

app/views/games/new.html.haml
.row
  .small-2.large-12.columns.center
    %h4 New Game
= form_tag("/games")
.row
  .small-2.large-4.columns.center
    %h4 Winner
    =select_tag "winner", options_from_collection_for_select(@players, "id", "name"), {:class => 'chzn-select-player', "data-placeholder" => 'Choose a player'}
    %h5 Secret
    =password_field_tag "winner_secret_key"


  .small-2.large-4.columns.center
    %h2 VS.
  .small-2.large-4.columns.center
    %h4 Loser
    =select_tag "loser", options_from_collection_for_select(@players, "id", "name"), {:class => 'chzn-select-player', "data-placeholder" => 'Choose a player'}
    %h5 Secret
    =password_field_tag "loser_secret_key"

.row.game-type
  .small-2.large-12.columns.center
    %h4 Gametype
    %select.winner{style: "width: 25%", :class => 'chzn-select-gametype', "data-placeholder" => "Gametype"}
      %option Eightball

.row.meta-fields
  .small-2.large-12.columns.center
    %h4 Rendataan metaa Gametypen mukaa
    %input{type: "text"}

.row.submit-button
  .small-2.large-12.columns.center
    = submit_tag "Create game record", class: 'button'

app/views/layouts/application.haml
!!! 5
-# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js ie6 oldie" lang="en">
/[if IE 7]    <html class="no-js ie7 oldie" lang="en">
/[if IE 8]    <html class="no-js ie8 oldie" lang="en">
/[if gt IE 8] <!--> <html class="no-js" lang="en"> <!-->
%head
  %meta{:charset => 'utf-8'}
  %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}

  %title= content_for?(:title) ? yield(:title) : "Ball-In-Hand"
  %meta{:name => 'description', :content => ''}
  %meta{:name => 'author', :content => ''}
  %meta{:name => 'viewport', :content => 'width=device-width,initial-scale=1'}

  = javascript_include_tag "application"

  -# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

  = stylesheet_link_tag "application"
  %link{:href => "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css", :rel => "stylesheet"}
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags

  %body
    = render "shared/header"

    .container
      = yield

    = render "shared/footer"

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>

    <%= f.label :secret_key %><br />
    <%= f.password_field :secret_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_form.html.haml
= form_for(@player) do |f|
  - if @player.errors.any?
    #error_explanation
      %h2
        = pluralize(@player.errors.count, "error")
        prohibited this player from being saved:
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/edit.html.haml
.row
	.large-12.columns
		<h1>Editing player</h1>

		= render 'form'

		= link_to 'Show', @player |
		= link_to 'Back', players_path

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/index.html.haml
.row
  .large-12.columns
    %h1 Listing players
    %table
      %tr
        %th Name
        %th
        %th
        %th
      - @players.each do |player|
        %tr
          %td= player.name
          %td= link_to 'Show', player
          %td= link_to 'Edit', edit_player_path(player)
          %td= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    = link_to 'New Player', new_player_path

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/new.html.haml
.row
	.large-12.columns
		<h1>New player</h1>

		= render 'form'

		= link_to 'All players', players_path, class: 'button'

app/views/players/show.html.haml
.row
  .large-12.columns
    %h1= @player.name

.row
  .large-12.columns
    %table
      %thead
        %tr
          %th Opponent
          %th Result
          %th New Ranking
          %th Played at
      %tbody
        - @player.results.each do |result|
          %tr
            %td= result.opponent.name
            - if result.won
              %td Won
            - else
              %td Lost
            %td= result.rating_after
            %td= result.created_at.localtime.strftime("%c")
          %td= result.opponent.name
          - if result.won
            %td Won
          - else
            %td Lost
          %td= result.rating_after
          %td= result.created_at.localtime.strftime("%c")

.row
  #data{style: "display: none"}
    .ratings #{@results.map(&:rating_after).to_json}
  #rating-chart{style: "margin-bottom: 50px;"}

:coffee
  $ ->
    ratings = JSON.parse($("#data .ratings").text())
    xAxis = [1..ratings.length]
    r = Raphael("rating-chart")
    console.log xAxis
    r.linechart(30,0,800,300, xAxis, ratings, smooth: true, symbol: 'circle', axis: '0 0 1 1')

app/views/shared/_footer.html.haml
%div#sticky_footer.text-center
  %p.footer-label KickAssFooter

app/views/shared/_header.html.haml
%nav.top-bar{:style => ""}
  %ul.title-area
    %li.name
      %h1
        %a{:href => "/"} Ball-In-Hand